spring:
  application:
    name: search-books

  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ocr:
  tesseract:
    data-path: src/main/resources/tessdata
    language: eng

logging:
  level:
    com.search.books: info
    web: info