spring:
  application:
    name: search-books

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ocr:
  tesseract:
    data-path: src/main/resources/tessdata
    language: kor+eng
    ocr-engine-mode: 1

logging:
  level:
    com.search.books: info
    web: info