spring:
  application:
    name: search-books

  profiles:
    active: prod

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

server:
  port: 8080

api:
  google-books:
    base-url: https://www.googleapis.com/books/v1
    api-key: ${GOOGLE_BOOKS_API_KEY}
    timeout: 30s

ocr:
  tesseract:
    data-path: ${OCR_TESSERACT_DATA_PATH:src/main/resources/tessdata}
    language: ${OCR_TESSERACT_LANGUAGE:eng}

logging:
  level:
    com.search.books: ${LOG_LEVEL_APP:info}